blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', Blog.as_view(), name='all_blogs'),
    path('<int:pk>/', Details.as_view(), name='details')
]

personalportfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls'))
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from .views import *

app_name = 'portfolio'

urlpatterns = [
    path('', HomePage.as_view(), name='home')
]

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class BlogPostModel(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        # пишем через blog:, потому что в юрлах мы указали, что имя нашего приложения blog. Тем самым, через blog: мы указываем, что ссылку надо искать именно в юрлах приложения blog. Тем самым избежим ошибки, если в разных приложениях будут ссылки с одинаковыми именами. Так же можно юзать и в {% url 'blog:details' blog.pk %}
        return reverse('blog:details', args=[self.pk,])

portfolio/models.py
from django.db import models

# Create your models here.

class PortfolioModel(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    photo = models.ImageField(upload_to='portfolio/images')
    link = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import *
# Create your views here.


class Blog(ListView):
    model = BlogPostModel
    template_name = 'blog/home.html'
    context_object_name = 'blog_item'


class Details(DetailView):
    model = BlogPostModel
    template_name = 'blog/detail.html'
    context_object_name = 'blog_item'
# ^
# |
# def detail(request, pk):
#     blog = get_object_or_404(BlogPostModel, pk=pk)
#     return render(request, 'blog/detail.html', {"blog_item":blog})

portfolio/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import *
# Create your views here.


class HomePage(ListView):
    model = PortfolioModel
    template_name = 'portfolio/home_page.html'
    context_object_name = 'item'

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}
<h1> {{blog_item.title}} </h1>
<br>
<h2> {{blog_item.content}} </h2>
<br>
<h3> ----- {{blog_item.created_at|date:'F jS Y'}} ----- </h3>
{% endblock content %}

blog/templates/blog/home.html
{% extends 'base.html' %}
{% block content %}
<h1>You have written {{blog_item.count}} post{{blog_item.count|pluralize}}</h1>

{% for post in blog_item %}
<a href="{{post.get_absolute_url}}"><h1>{{ post.title }}</h1></a>

<h2> {{ post.content|truncatechars:50 }} </h2>
<h3> {{ post.created_at|date:'F jS Y'}}</h3>
{% endfor %}
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'portfolio/logo.jpg' %}" type="image/jpg">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Alkatra&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  </head>
  <body>
    {% include 'inc/_nav.html' %}
    {% block content %} CONTENT {% endblock content %}
    {% include 'inc/_footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

templates/inc/_footer.html
 <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Web design</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Hosting</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Portfolio</a></li>
                            <li><a href="#">Basic information</a></li>
                            <li><a href="#">Resume</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Company Name</h3>
                        <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">Yevhenii Tunyk © 2023</p>
            </div>
        </footer>
    </div>

templates/inc/_nav.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark mb-5" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'portfolio:home' %}"><img src="{% static 'portfolio/logo.jpg' %}" alt="" width="30" height="24"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'portfolio:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% static 'portfolio/WBA_Tunyk.pdf' %}" target="_blank">Resume</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            How to contact me
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="mailto:yevhtunyl@gmail.com?cc=saddadnowisdead@gmail.com" target="_blank">Mail</a></li>
            <li><a class="dropdown-item" href="tg://resolve?domain=saddadnowisdead">Telegram</a></li>
            <li><a class="dropdown-item" href="tel:+4915164877296">Phone: +4915164877296</a></li>
            <li><a class="dropdown-item" href="viber://chat?number=+380633483426">Viber</a></li>
            <li><a class="dropdown-item" href="https://www.instagram.com/saddadnowisdead" target="_blank">Instagram</a></li>
            <li><a class="dropdown-item" href="https://api.whatsapp.com/send?phone=380633483426" target="_blank">WhatsApp</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form> -->
  </div>
</nav>